### ISSUE TITLE
Issue rendering span in index

### ISSUE THREAD

**Issue by tomcollins** [dvla/dvla.github.io#22]
This appears to be caused by a change to hugo. 

We use "latest" in the github action. 

I was able to reproduce locally after upgrading hugo from 0.110.0 -> 0.120.4.
  
![image](https://github.com/dvla/dvla.github.io/assets/642437/06c85a8d-e5d7-4aed-9869-76a209fd6bc0)

**Comment by devonwhale** [comment]
Just for reference, this has been unpinned in PR #37 as we were starting to run into compatibility issues with Hugo and newer versions of PaperMod. The latest version of Hugo doesn't have the issue this pin was used to prevent

<img width="759" alt="Image" src="https://github.com/user-attachments/assets/e5561ec1-a9ad-4373-b900-52e7857c0c46" />
